<a href="https://colab.research.google.com/github/shwethashaji-ai/cognifyzTech_ML/blob/main/Cuisine_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [7]:
# Read the dataset
data = pd.read_csv("/content/Dataset .csv")
data


Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

In [8]:
data.head(5)

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [9]:
# Handle missing values using forward fill
data.fillna(method='ffill', inplace=True)
data

<ipython-input-9-478d698e67df>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)


Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

In [10]:
print(data.columns)
print(data.head())


Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')
   Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chin

In [11]:
# Encode the target variable 'Cuisines'
encoder = LabelEncoder()
data['Cuisines'] = encoder.fit_transform(data['Cuisines'])


In [12]:
# Selecting relevant features for model training
selected_features = ['Price range', 'Aggregate rating', 'Votes']  # Modify as needed
feature_data = data[selected_features]
feature_data


Price range  Aggregate rating  Votes
0               3               4.8    314
1               3               4.5    591
2               4               4.4    270
3               4               4.9    365
4               4               4.8    229
...           ...               ...    ...
9546            3               4.1    788
9547            3               4.2   1034
9548            4               3.7    661
9549            4               4.0    901
9550            2               4.0    591

[9551 rows x 3 columns]

In [13]:
# Splitting data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(feature_data, data['Cuisines'], test_size=0.2, random_state=42)

In [16]:
X_train

Price range  Aggregate rating  Votes
1115            3               3.3     56
7633            1               3.0      4
8267            1               0.0      0
7209            1               0.0      1
6242            2               2.5     75
...           ...               ...    ...
5734            1               0.0      0
5191            2               3.8     75
5390            1               0.0      0
860             4               4.4     66
7270            2               3.7    195

[7640 rows x 3 columns]

In [14]:
X_test

Price range  Aggregate rating  Votes
4731            1               2.1     54
1468            2               4.1     84
9037            2               3.2     36
7866            1               4.4    163
5570            1               3.5     14
...           ...               ...    ...
8149            2               2.6     44
5849            1               0.0      1
9019            2               3.1     10
742             3               4.2    334
180             3               4.3    428

[1911 rows x 3 columns]

In [15]:
y_train

1115    1406
7633     828
8267    1262
7209     782
6242    1514
        ... 
5734    1329
5191    1514
5390    1699
860     1498
7270    1514
Name: Cuisines, Length: 7640, dtype: int64

In [17]:
y_test

4731    1306
1468    1284
9037    1514
7866     828
5570    1514
        ... 
8149    1520
5849    1306
9019     518
742      625
180     1022
Name: Cuisines, Length: 1911, dtype: int64

In [18]:
# Initialize and train a random forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [19]:
# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred


array([ 177, 1796, 1699, ...,  549, 1689,  154])

In [21]:
# Evaluate model performance
print(f'Accuracy Score: {accuracy_score(y_test, y_pred):.2f}')



Accuracy Score: 0.08


In [22]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         5
           8       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         1
          23       0.00      0.00      0.00         0
          24       0.00      0.00      0.00         1
          27       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          38       0.00      0.00      0.00         1
          40       0.00    

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

In [23]:
print(confusion_matrix(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
# Display the mapping of cuisines
cuisine_list = dict(zip(encoder.classes_, range(len(encoder.classes_))))
print("Cuisine Mapping:", cuisine_list)

Cuisine Mapping: {'Afghani': 0, 'Afghani, Mughlai, Chinese': 1, 'Afghani, North Indian': 2, 'Afghani, North Indian, Pakistani, Arabian': 3, 'African': 4, 'African, Portuguese': 5, 'American': 6, 'American, Asian, Burger': 7, 'American, Asian, European, Seafood': 8, 'American, Asian, Italian, Seafood': 9, 'American, Asian, North Indian, Mexican, South Indian': 10, 'American, BBQ': 11, 'American, BBQ, Burger': 12, 'American, BBQ, Sandwich': 13, 'American, BBQ, Seafood': 14, 'American, BBQ, Southern': 15, 'American, BBQ, Steak': 16, 'American, Bakery, European, Burger, Fusion': 17, 'American, Bar Food': 18, 'American, Bar Food, BBQ': 19, 'American, Bar Food, Sandwich': 20, 'American, Breakfast': 21, 'American, Breakfast, Burger': 22, 'American, Breakfast, Desserts': 23, 'American, Breakfast, Diner': 24, 'American, Breakfast, Greek': 25, 'American, Breakfast, Hawaiian': 26, 'American, Breakfast, Vegetarian': 27, 'American, British, Continental': 28, 'American, Burger': 29, 'American, Burge

In [27]:

# Create a DataFrame for the mapping
cuisine_mapping_df = pd.DataFrame({'Cuisine': encoder.classes_, 'Numerical Label': range(len(encoder.classes_))})

# Display the DataFrame
print(cuisine_mapping_df)

                                        Cuisine  Numerical Label
0                                       Afghani                0
1                     Afghani, Mughlai, Chinese                1
2                         Afghani, North Indian                2
3     Afghani, North Indian, Pakistani, Arabian                3
4                                       African                4
...                                         ...              ...
1820                       Western, Asian, Cafe             1820
1821                 Western, Fusion, Fast Food             1821
1822                              World Cuisine             1822
1823            World Cuisine, Mexican, Italian             1823
1824            World Cuisine, Patisserie, Cafe             1824

[1825 rows x 2 columns]


In [28]:

# Print the mapping with formatting
for cuisine, label in cuisine_list.items():
    print(f"{cuisine}: {label}")

Afghani: 0
Afghani, Mughlai, Chinese: 1
Afghani, North Indian: 2
Afghani, North Indian, Pakistani, Arabian: 3
African: 4
African, Portuguese: 5
American: 6
American, Asian, Burger: 7
American, Asian, European, Seafood: 8
American, Asian, Italian, Seafood: 9
American, Asian, North Indian, Mexican, South Indian: 10
American, BBQ: 11
American, BBQ, Burger: 12
American, BBQ, Sandwich: 13
American, BBQ, Seafood: 14
American, BBQ, Southern: 15
American, BBQ, Steak: 16
American, Bakery, European, Burger, Fusion: 17
American, Bar Food: 18
American, Bar Food, BBQ: 19
American, Bar Food, Sandwich: 20
American, Breakfast: 21
American, Breakfast, Burger: 22
American, Breakfast, Desserts: 23
American, Breakfast, Diner: 24
American, Breakfast, Greek: 25
American, Breakfast, Hawaiian: 26
American, Breakfast, Vegetarian: 27
American, British, Continental: 28
American, Burger: 29
American, Burger, Cafe: 30
American, Burger, Cajun: 31
American, Burger, Fast Food: 32
American, Burger, Grill: 33
American,